version: '3.3'

services:
  oco2:
    build: ./
    ports:
      # local : distant
      - 7901:8050 # Dash
      - 7988:8888 # Jupyter
    environment:
      MAPBOX_TOKEN: "my_token"
      HOME_DIR: "/opt/oco2peak/"
    volumes: 
        - type: bind
          source: ./configs
          target: /opt/oco2peak/configs
        - type: bind
          source: ./notebooks
          target: /opt/oco2peak/notebooks
        - type: bind
          source: ./oco2peak
          target: /opt/oco2peak/oco2peak
        - type: bind
          source: ./front
          target: /opt/oco2peak/front