# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Datasets": "swift_utils.ipynb"}

modules = ["datasets.py"]

doc_url = "https://trancept.github.io/oco2peak/"

git_url = "https://github.com/trancept/oco2peak/tree/master/"

def custom_doc_links(name): return None
